### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by konsumer** [ABuffSeagull/parcel-plugin-prerender#2]
I get this error:

```
TypeError: Cannot read property 'map' of undefined
    at PuppeteerRenderer.renderRoutes (/Users/konsumer/Desktop/parcel-ssr/node_modules/@prerenderer/renderer-puppeteer/es6/renderer.js:82:14)
    at Prerenderer.renderRoutes (/Users/konsumer/Desktop/parcel-ssr/node_modules/@prerenderer/prerenderer/es6/index.js:108:27)
    at Bundler.bundler.on (/Users/konsumer/Desktop/parcel-ssr/node_modules/parcel-plugin-prerender/index.js:24:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

with this`prerender.config.js`:

```
module.exports = [
  '/',
  '/about',
  '/terms',
  '/features',
  '/stories',
  '/pricing'
]
```

I made this [demo](https://github.com/konsumer/parcel-ssr) to illustrate the issue.

**Comment by ABuffSeagull** [comment]
Ah yeah, you just need to put the routes in a `routes` key.
```
module.exports = {
  routes: [
    '/',
    '/about',
    '/terms',
    '/features',
    '/stories',
    '/pricing'
  ]
}
```
Although you made me realize that the README is wrong. Thanks for bringing it up!
(I just might also make it if there's no key, accept it as the routes anyway)

**Comment by konsumer** [comment]
aha! thank you.
